capp/carbon_app/forms.py
from flask_wtf import FlaskForm
from wtforms import  SubmitField,  SelectField,  FloatField
from wtforms.validators import InputRequired

class BusForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Diesel', 'Diesel'), ('BioDiesel', 'BioDiesel'), ('Electric', 'Electric')])
  submit = SubmitField('Submit')

class CarForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'),('Electric','Electric')])
  submit = SubmitField('Submit')  

class PlaneForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('Gasoline', 'Gasoline')])
  submit = SubmitField('Submit')

class TrainForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('No Fossil Fuel', 'No Fossil Fuel')])
  submit = SubmitField('Submit')

class ElkickScooterForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('No Fossil Fuel', 'No Fossil Fuel')])
  submit = SubmitField('Submit') 

class ElBicycleForm(FlaskForm):
  kms = FloatField('Kilometers', [InputRequired()])
  fuel_type = SelectField('Type of Fuel', [InputRequired()], 
    choices=[('No Fossil Fuel', 'No Fossil Fuel')])
  submit = SubmitField('Submit') 

capp/carbon_app/__init__.py
#

capp/carbon_app/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from capp.models import Transport
from capp import db
from datetime import timedelta, datetime
from flask_login import login_required, current_user
from capp.carbon_app.forms import BusForm, CarForm, PlaneForm, TrainForm, ElkickScooterForm, ElBicycleForm
import json

carbon_app=Blueprint('carbon_app',__name__)

#Emissions factor per transport in kg per passemger km
#Data from: http://efdb.apps.eea.europa.eu/?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22display_type%22%3A%22tabular%22%7D
efco2={'Bus':{'Diesel':0.855,'BioDiesel':0.014,'Electric':0.067},
    'Car':{'Gasoline':0.157,'Diesel':0.130,'Hybrid':0.152,'No Fossil Fuel':0.0776},
    'Plane':{'Gasoline':0.298},
    'Train':{'No Fossil Fuel':0.045},
    'ElkickScooter':{'No Fossil Fuel':0.002328},
    'ElBicyle':{'No Fossil Fuel':0.002327}}


#Carbon app, main page
@carbon_app.route('/carbon_app')
@login_required
def carbon_app_home():
    return render_template('carbon_app/carbon_app.html', title='carbon_app')

#New entry bus
@carbon_app.route('/carbon_app/new_entry_bus', methods=['GET','POST'])
@login_required
def new_entry_bus():
    form = BusForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Bus'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        total = co2

        co2 = float("{:.2f}".format(co2))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_bus.html', title='new entry bus', form=form)

#New entry car
@carbon_app.route('/carbon_app/new_entry_car', methods=['GET','POST'])
@login_required
def new_entry_car():
    form = CarForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Car'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        total = co2

        co2 = float("{:.2f}".format(co2))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_car.html', title='new entry car', form=form)    

#New entry plane
@carbon_app.route('/carbon_app/new_entry_plane', methods=['GET','POST'])
@login_required
def new_entry_plane():
    form = PlaneForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Plane'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        total = co2

        co2 = float("{:.2f}".format(co2))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_plane.html', title='new entry plane', form=form)  

#New entry Train
@carbon_app.route('/carbon_app/new_entry_train', methods=['GET','POST'])
@login_required
def new_entry_train():
    form = TrainForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'Train'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        total = co2

        co2 = float("{:.2f}".format(co2))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_train.html', title='new entry Train', form=form)     

#New entry ElkickScooter
@carbon_app.route('/carbon_app/new_entry_ElkickScooter', methods=['GET','POST'])
@login_required
def new_entry_ElkickScooter():
    form = ElkickScooterForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'ElkickScooter'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        total = co2

        co2 = float("{:.2f}".format(co2))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_ElkickScooter.html', title='new entry motorbike', form=form) 

#New entry ElBicyleForm
@carbon_app.route('/carbon_app/new_entry_ElBicyle', methods=['GET','POST'])
@login_required
def new_entry_ElBicycle():
    form = ElBicycleForm()
    if form.validate_on_submit():
        kms = form.kms.data
        fuel = form.fuel_type.data
        transport = 'ElBicyle'
        # kms = request.form['kms']
        # fuel = request.form['fuel_type']

        co2 = float(kms) * efco2[transport][fuel]
        total = co2

        co2 = float("{:.2f}".format(co2))
        total = float("{:.2f}".format(total))

        emissions = Transport(kms=kms, transport=transport, fuel=fuel, co2=co2, total=total, author=current_user)
        db.session.add(emissions)
        db.session.commit()
        return redirect(url_for('carbon_app.your_data'))
    return render_template('carbon_app/new_entry_Elbicycle.html', title='new entry Elbicycle', form=form)


#Your data
@carbon_app.route('/carbon_app/your_data')
@login_required
def your_data():
    #Table
    entries = Transport.query.filter_by(author=current_user). \
        filter(Transport.date> (datetime.now() - timedelta(days=5))).\
        order_by(Transport.date.desc()).order_by(Transport.transport.asc()).all()
    #Emissions by category
    emissions_by_transport = db.session.query(db.func.sum(Transport.total), Transport.transport). \
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user). \
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    emission_transport = [0, 0, 0, 0, 0, 0,0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in emissions_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])

    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        emission_transport[1]=first_tuple_elements[index_bus]
    else:
        emission_transport[1]

    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        emission_transport[2]=first_tuple_elements[index_car]
    else:
        emission_transport[2]

    if 'Plane' in second_tuple_elements:
        index_plane = second_tuple_elements.index('Plane')
        emission_transport[3]=first_tuple_elements[index_plane]
    else:
        emission_transport[3]

    if 'Train' in second_tuple_elements:
        index_train = second_tuple_elements.index('Train')
        emission_transport[4]=first_tuple_elements[index_train]
    else:
        emission_transport[4]

    if 'ElkickScooter' in second_tuple_elements:
        index_scooter= second_tuple_elements.index('ElkickScooter')
        emission_transport[5]=first_tuple_elements[index_scooter]
    else:
        emission_transport[5]

    if 'ElBicyle' in second_tuple_elements:
        index_bike= second_tuple_elements.index('ElBicyle')
        emission_transport[6]=first_tuple_elements[index_bike]
    else:
        emission_transport[6]

    #Kilometers by category
    kms_by_transport = db.session.query(db.func.sum(Transport.kms), Transport.transport). \
        filter(Transport.date > (datetime.now() - timedelta(days=5))).filter_by(author=current_user). \
        group_by(Transport.transport).order_by(Transport.transport.asc()).all()
    kms_transport = [0, 0, 0, 0, 0, 0,0]
    first_tuple_elements = []
    second_tuple_elements = []
    for a_tuple in kms_by_transport:
        first_tuple_elements.append(a_tuple[0])
        second_tuple_elements.append(a_tuple[1])

    if 'Bus' in second_tuple_elements:
        index_bus = second_tuple_elements.index('Bus')
        kms_transport[0]=first_tuple_elements[index_bus]
    else:
        kms_transport[0] 

    if 'Car' in second_tuple_elements:
        index_car = second_tuple_elements.index('Car')
        kms_transport[1]=first_tuple_elements[index_car]
    else:
        kms_transport[1]

    if 'Plane' in second_tuple_elements:
        index_plane = second_tuple_elements.index('Plane')
        kms_transport[2]=first_tuple_elements[index_plane]
    else:
        kms_transport[2]

    if 'Train' in second_tuple_elements:
        index_train = second_tuple_elements.index('Train')
        kms_transport[3]=first_tuple_elements[index_train]
    else:
        kms_transport[3]

    if 'ElkickScooter' in second_tuple_elements:

capp/home/__init__.py
#

capp/home/routes.py
from flask import render_template, Blueprint
from capp.models import User, Transport

home=Blueprint('home',__name__)

@home.route('/')
@home.route('/home')
def home_home():
  # Query 1: Kilometers by user
  username = 'Fjell'
  user_id = User.query.filter_by(username=username).first().id
  user_name= User.query.filter_by(username=username).first().username
  user_transports = Transport.query.filter_by(user_id=user_id).all()
 
  # Query 2: Co2 per kilometer by user 
  username = 'Fjell'
  user_id = User.query.filter_by(username=username).first().id
  user_name= User.query.filter_by(username=username).first().username
  user_transports = Transport.query.filter_by(user_id=user_id).all()
  kms = []
  co2 = []
  for transport in user_transports:
    (kms.append(round(transport.kms)))
    (co2.append(round(transport.co2)))  
  co2_kms = []
  len_list = len(kms)
  for i in range(len_list):
      co2_kms.append(round((co2[i]/kms[i]),3))
 

  return render_template('home.html', user_transports=user_transports, user_name=user_name, kms=kms, 
                         co2=co2, co2_kms=co2_kms)

capp/methodology/__init__.py
#

capp/methodology/routes.py
from flask import render_template, Blueprint

methodology=Blueprint('methodology',__name__)

@methodology.route('/methodology')
def methodology_home():
  return render_template('methodology.html', title='methodology')

capp/users/routes.py
from flask import render_template, Blueprint, redirect, flash, url_for, request
from capp.users.forms import RegistrationForm, LoginForm
from capp.models import User
from capp import db, bcrypt
from flask_login import login_user, current_user, logout_user

users=Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.home_home'))
  if form.validate_on_submit():
      user_hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user = User(username=form.username.data, email=form.email.data, password=user_hashed_password)
      db.session.add(user)
      db.session.commit()
      flash('Your account has been created! Now, you are able to login!', 'success')
      return redirect(url_for('users.login'))
  return render_template('users/register.html', title='register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.home_home'))
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        next_page=request.args.get('next')
        flash('You have logged in! Now, you can start to use the carbon app!', 'success')
        return redirect(next_page) if next_page else redirect(url_for('home.home_home'))
    else:
        flash('Login Unsuccessful. Please check email and password!', 'danger')  
  return render_template('users/login.html', title='login', form=form)

@users.route('/logout')
def logout():    
    logout_user()
    flash('You have logged out', 'success')
    return redirect(url_for('home.home_home'))

capp/templates/carbon_app.html
{% extends "layout.html" %}
{% block content %}

    <!-- Header -->
    <section class="section_header_carbon_app">
        <div class="container">
    
        <div class="header_carbon_app">
            <div class="box"> 
            <h1 style="font-size:55px;"><span class="text-logo"> Carbon App Calculator</span></h1>
            <p style="text-align:left;">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat dolores quos asperiores repellendus facilis cum illo aperiam odit doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente quisquam consectetur optio magnam voluptates omnis vel officia alias distinctio quas laborum reiciendis ratione inventore veniam, cupiditate doloribus dolore, eius natus a. Magni inventore consequuntur voluptas reprehenderit perferendis! Molestias aspernatur rem autem aut temporibus.
            </p>
            <div class="container_buttons_links_header_carbon_app">
                <div class="btn">
                    <a href="{{url_for('methodology.methodology_home')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#FF7F00;">Methodology</a>
                </div>
                <div class="btn">
                    <a href="{{url_for('carbon_app.your_data')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#FF7F00;">Your Data</a>
                </div>
                <div class="btn">
                    <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:#FF7F00;", data-toggle="modal" data-target="#carbon_app_instructions">Instructions</a>
                </div>
            </div>  
            <!-- Modal Instructions -->
            <div class="modal fade" id="carbon_app_instructions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
          
                    <div class="modal-header">
                    <h5 class="modal-title", style="color:black; text-align: center;">Carbon App, instructions</h5>
                    </div>
          
                    <div class="modal-body", style="color:black">
                    <p style="text-align: left;">
                        Welcome to the carbon app, here is the instruction for using our application. First choose your mode of transportation.
                    </p>
                    <ol style="text-align:left;">
                        <li>
                            Enter the number of kilometers you have travelled.
                        </li>
                        <li>
                            Choose the type of fuel that your transportation used.
                        </li>
                    </ol>
                    </div>
          
                </div>
                </div>
            </div>
            </div>
            <div class="box">
            <img 
                src="{{url_for('static', filename='icons/Carbon_calculator_3.svg')}}"
                width="325" 
                height="325"
                alt=""/>
            </div>
        </div>
    </section>
<section class="section_carbon_app_new_entry_main">
    <div class="container">
  
      <div class="carbon_app_new_entry_main" style="display:block;">
        <br>
        <h3 style="text-align:center;">Please, select your mean of conveyance in the boxes below</h3>     
      </div>
  
      <div class="carbon_app_new_entry_main">
          <div class="box">
            <div class="h1 mb-3" style="text-align: center;">
                <i class="fa-solid fa-bus"></i>
            </div>
            <h3>Bus</h3>
            <p>Please, enter your kilometers by using the bus.
            </p>
            <div class="section_container_buttons_carbon_app_new_entry_main">
              <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_bus')}}">New Entry</a>
            </div> 
          </div>
          <div class="box">
            <div class="h1 mb-3" style="text-align: center;">
                <i class="fa-solid fa-car"></i>
            </div>
            <h3>Car</h3>
            <p>Please, enter your kilometers by using the car.
            </p>
            <div class="section_container_buttons_carbon_app_new_entry_main">
              <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_car')}}">New Entry</a>
            </div> 
          </div>           
          <div class="box">
            <div class="h1 mb-3" style="text-align: center;">
                <i class="fa-solid fa-plane"></i>
            </div>
            <h3>Plane</h3>
            <p>Please, enter your kilometers by using the plane.
            </p>
            <div class="section_container_buttons_carbon_app_new_entry_main">
              <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_plane')}}">New Entry</a>
            </div> 
          </div>
          <div class="box">
            <div class="h1 mb-3" style="text-align: center;">
                <i class="fa-solid fa-ship"></i>
            </div>
            <h3>Train</h3>
            <p>Please, enter your kilometers by using the Train.
            </p>
            <div class="section_container_buttons_carbon_app_new_entry_main">
              <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_train')}}">New Entry</a>
            </div> 
          </div>      
      </div>

      <div class="carbon_app_new_entry_main">
        <div class="box">
          <div class="h1 mb-3" style="text-align: center;">
            <i class="fa-solid fa-motorcycle"></i>
          </div>
          <h3>Eletric Scooter</h3>
          <p>Please, enter your kilometers by using the eletric scooter.
          </p>
          <div class="section_container_buttons_carbon_app_new_entry_main">
            <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_ElkickScooter')}}">New Entry</a>
          </div> 
        </div>    
        <div class="box">
          <div class="h1 mb-3" style="text-align: center;">
            <i class="fa-solid fa-bicycle"></i>
          </div>
          <h3>Electric Bicycle</h3>
          <p>Please, enter your kilometers by using the eletric bicycle.
          </p>
          <div class="section_container_buttons_carbon_app_new_entry_main">
            <a class="btn_carbon_app_new_entry_main" href="{{url_for('carbon_app.new_entry_ElBicycle')}}">New Entry</a>
          </div> 
        </div>     
         
    </div>  
    <div class="box" style="background-color:#BACEC1;">
    </div>      
             
</section> 
       

{% endblock content %}

capp/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
      <!-- Font Awesome code -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

 
      <!--Import the Bootstrap CSS file:-->
 <link
 href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
 rel="stylesheet"
 integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
 crossorigin="anonymous"
 />
 <link
   rel="stylesheet"
   href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
 />

 <!-- Matjax -->
 <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
 <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

      <!-- CSS code -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='methodology.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='carbon_app.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='your_data.css') }}">


      <!-- To activate media queries in devices -->
      <meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1">
        {% if title %}
            <title>{{ title }}</title>
        {% else %}
            <title>home</title>
        {% endif %}
        
       <!-- java utility -->
       <script src="{{ url_for('static', filename='java_utility.js') }}"></script>

      <!--For the plots-->
      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
      <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->

    </head>
    <body>
    
        <section class="section_navbar">
          <br>
          <div class="container">
            <div class="navbar">
              <h1 class="logo">
                <a href="{{url_for('home.home_home')}}">
                  <span class="text-logo" style="font-size: 50px;"><i class="fa-solid fa-leaf" style="color: #FF7F00;"></i> CarbonApp</span>
              </a>
              </h1>
              {% if current_user.is_authenticated %}
              <nav>
                <ul>
                    <li>
                        <a href="{{url_for('home.home_home')}}"><i class="fa-solid fa-house"></i> Home</a>
                    </li>
                    <li>
                        <a href="{{url_for('methodology.methodology_home')}}"> <i class="fa-solid fa-info"></i> Methodology</a>
                    </li>
                    <li>
                        <a href="{{url_for('carbon_app.carbon_app_home')}}"> <i class="fa-solid fa-calculator"></i> Carbon App</a>
                    </li>
                    <li>
                      <a href="{{url_for('users.logout')}}"> <i class="fa-solid fa-arrow-right-to-bracket"></i> Logout</a>
                  </li>
                    
                </ul>
              </nav> 
              {%else%}
              <nav>
                <ul>
                    <li>
                        <a href="{{url_for('home.home_home')}}"><i class="fa-solid fa-house"></i> Home</a>
                    </li>
                    <li>
                        <a href="{{url_for('methodology.methodology_home')}}"> <i class="fa-solid fa-info"></i> Methodology</a>
                    </li>
                    <li>
                        <a href="{{url_for('carbon_app.carbon_app_home')}}"> <i class="fa-solid fa-calculator"></i> Carbon App</a>
                    </li>
                    <li>
                      <a href="{{url_for('users.register')}}"> <i class="fa-regular fa-address-card"></i> Register</a>
                  </li>
                    <li>
                      <a href="{{url_for('users.login')}}"> <i class="fa-solid fa-arrow-right-to-bracket"></i> Login</a>
                    </li>
                </ul>
              </nav>
              {%endif%}
              
            </div>
          </div>
          <br>
        </section>

        {% block content %} {% endblock %}
        <section class="section_footer">
          <div class="container">
            <div class="footer">
              <br>
              <br>
            <div class="icon-footer" style="text-align: center;">
              <h1>
                Carbon App 
                <a href="#">
                  <i class="fa-solid fa-circle-up" style="color: #FF7F00"></i>
                </a>
                <br>
                <br>
              </h1>
            </div>
            </div>
          </div>
        </section>

        <!-- Bootstrap -->
        <!-- Question Accordion -->
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"
        ></script>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
    </body>
</html>